config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only: [:new, :create, :destroy]
  resources :bookmarks, only: [:index, :create, :destroy]
  resources :friendships, only: :show

  root 'sessions#new'
  get 'logout', to: 'sessions#destroy'
  get 'friends', to: 'friendships#index'

  get '/auth/:provider/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
	mount_uploader :preview, PreviewUploader
	
	belongs_to :user

	validates :url, presence: true, :uniqueness => {:scope => :user_id}

	def self.search(search, user_id)
	  if search.blank?
	  	bookmarks = Bookmark.where(user_id: user_id).sort
	  else
	    bookmarks = Bookmark.select{|bookmark| bookmark.url.split("//").last.include?(search) && bookmark.user_id == user_id }
	  end
	end

	def check_url_and_add_preview(unvalid_url)
		url = unvalid_url.remove(/[ ]*/).sub(/[\/]+$/, '')
		self.url = url

		if url.length != 0
			unless (url.start_with?("https://") || url.start_with?("http://"))
				self.url.insert(0, "https://")
			end
		end

		self.preview = CreateScreenshot.new(url).create_screen
	end

end

app/models/friendship.rb
class Friendship < ApplicationRecord
	belongs_to :user
	belongs_to :friend, foreign_key: 'friend_id', class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
	has_many :bookmarks, dependent: :delete_all
	has_many :friendships
	has_many :friends, through: :friendships, foreign_key: 'friend_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def authorized?
  	redirect_to root_path unless current_user
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end


  def per_page
	  per_page = 8	
  end

  def current_page(page)
  	page = 1.to_s if page.to_i == 0 || page.to_i < 0
  	return page
  end

  helper_method :current_user
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
	before_action :authorized?
	before_action :current_bookmark, only: :destroy

	require 'will_paginate/array'
	require 'create_screenshot_controller.rb'

	def index
		current_user_bookmarks = current_user.bookmarks.search(params[:search], current_user.id)
		@bookmarks = current_user_bookmarks.paginate(:page => current_page(params[:page]), :per_page => per_page)
	end

	def create
		bookmark = current_user.bookmarks.new(bookmark_params)
		bookmark.check_url_and_add_preview(bookmark_params[:url])

		flash[:error] = bookmark.errors.full_messages.join(". ") unless bookmark.save

		redirect_to bookmarks_path
	end

	def destroy
		if @current_bookmark
			@current_bookmark.delete
		else
			flash[:error] = "Can't find this bookmark!"
		end
		redirect_to bookmarks_path
	end


	private

	def current_bookmark
		@current_bookmark = current_user.bookmarks.find(params[:id])
	end

	def new_bookmark
		@new_bookmark = current_user.bookmarks.new()
	end

	def bookmark_params
		params.require(:bookmark).permit(:url)
	end


	helper_method :new_bookmark
end

app/controllers/create_screenshot_controller.rb
class CreateScreenshot < ApplicationController

	def initialize(url)
		@url = url
	end

	def create_screen
		filename = @url.gsub("https://", "").gsub('/', '.')
		screenshot = Webshot::Screenshot.instance
		file_with_screen = screenshot.capture @url, "tmp/images/"+ filename +".png", width: 1024, height: 800
		return file_with_screen
	end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	before_action :authorized?
	before_action :current_friend, only: :show

	def index
		@friends = current_user.friends
	end

	def show
		current_friend_bookmarks = @current_friend.bookmarks.search(params[:search], @current_friend.id)
		@bookmarks = current_friend_bookmarks.paginate(:page => current_page(params[:page]), :per_page => per_page)
	end

	private

	def current_friend
		@current_friend = User.find(params[:id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	before_action :find_or_create_user, only: :create
	before_action :find_user_friends, only: :create

	def new
		
	end

	def create
		session[:user_id] = @user.id
		redirect_to bookmarks_path
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_path
	end


	private

	def auth_params
		request.env['omniauth.auth']
	end

	def find_or_create_user
		@user = User.find_or_create_by(uid: auth_params[:uid], email: auth_params[:info][:email])
	end

	def find_user_friends
		graph = Koala::Facebook::API.new(auth_params[:credentials][:token])
		user_friends = graph.get_connection("me", "friends")

		user_friends.each do |friend|
			user_friend = User.find_by(uid: friend["id"])
			@user.friendships.find_or_create_by(friend_id: user_friend.id)
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_label_without_protocol(url)
		url_without_protocol = url.remove(/^https?:\/\//, "")

		link = content_tag(:a, url_without_protocol, href: "#{url}")
		return link
	end

  def show_image(img)

    if img.file.nil?
      html_img = image_tag(img, class: "bookmark_image_link default_img")
    else
      html_img = image_tag(img, class: "bookmark_image_link")
    end

    return html_img
  end

end

app/views/bookmarks/_find_bookmark_form.html.erb
<%= form_tag bookmarks_path, method: :get, id: 'bookmark_find_form' do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search" %>
	<%= submit_tag '', name: nil, id: 'find_bookmark_submit', title: "Search" %>
<% end %>

<button id = "reset_find_bookmark_form" title="Reset"><div></div>Reset</button>

app/views/bookmarks/_form.html.erb
<%= form_for new_bookmark, url: bookmarks_path, method: :post do |f| %>
	<%= f.text_field :url, placeholder: "Url"  %>
	<%= f.submit 'Add url', id: 'bookmark_submit' %>
<% end %>

app/views/bookmarks/index.html.erb
<header>
	<div id="top_menu_left">
		<%= link_to 'Friends', friends_path %>
	</div>

	<div class="top_menu_middle">
		<a id="add_new_bookmark_btn" class="top_menu_middle_link">New bookmark</a>
	</div>

	<div class="top_menu_middle">
		<%= link_to 'Logout', logout_path, class: "top_menu_middle_link" %>
	</div>
</header>

<div id="hidden_new_bookmark_form" class="unvisible">
	<%= render 'form', new_bookmark: new_bookmark %>
</div>

<div id ="main_bookmarks">

	<div class="horizontal_center">
		<div id = "error_message">
			
			<% if flash[:error] %>
				<div id ="hide_error_messages">
					<%= flash[:error] %>
					<div id="error_close_btn">X</div>
				</div>
			<% end %>

		</div>
	</div>


	<div class="horizontal_center">
		<%= render 'find_bookmark_form' %>
	</div>

	<div id = "bookmarks">
		<% if @bookmarks.size.zero? %>
			<div>No one bookmarks found!</div>
		<% else %>
			<% @bookmarks.each do |bookmark| %>

				<div class="bookmark">
					<%= link_to "", bookmark ,method: :delete, data: {confirm: "Delete this bookmark?"}, class: "delete_bookmark" %>
					<div class="bookmark_image"><%= show_image(bookmark.preview) %></div>
					<div class="bookmark_url"><%= link_label_without_protocol(bookmark.url) %></div>
				</div>

			<% end %>
		<% end %>
	</div>

	<div class = "apple_pagination">
		<%= will_paginate @bookmarks %>
	</div>
</div>

app/views/friendships/_find_friend_bookmark.html.erb
<%= form_tag friendship_path(@current_friend), method: :get, id: 'bookmark_find_form' do %>
	<%= text_field_tag :search, params[:search], placeholder: "Search" %>
	<%= submit_tag '', name: nil, id: 'find_bookmark_submit', title: "Search" %>
<% end %>

<button id = "reset_find_bookmark_form" title="Reset"><div></div>Reset</button>

app/views/friendships/index.html.erb
<div id="top_menu_left">
	<%= link_to 'Back', bookmarks_path %>
</div>

<div id="friends">
	<% @friends.each do |friend| %>

		<div class="friend">
			<span class="user_email"><%= friend.email %></span> <div class="friend_bookmarks"><%= link_to 'Bookmarks', friendship_path(friend) %></div>
		</div>

	<% end %>
</div>

app/views/friendships/show.html.erb
<div id="top_menu_left">
	<%= link_to "Back", friends_path %> 
</div>

<div id="user_email_parrent"><span class="user_email_middle_top"><%= @current_friend.email %></span></div>

<p id = "find_friend_bookmark_indent">
	<div class="horizontal_center">
		<%= render 'find_friend_bookmark' %>
	</div>

<div id="bookmarks">
	<% if @bookmarks.size.zero? %>
		<div>No one bookmarks found!</div>
	<% else %>
		<% @bookmarks.each do |bookmark| %>

			<div class="bookmark">
				<div class="bookmark_image"><%= show_image(bookmark.preview) %></div>
				<div class="bookmark_url"><%= link_to bookmark.url, bookmark.url %></div>
			</div>

		<% end %>
	<% end %>
</div>

<div class = "apple_pagination">
	<%= will_paginate @bookmarks, :container => false %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookmarks</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>